post/post/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts_app/urls.py
from django.contrib import admin
from django.urls import path
from posts_app import views

# blog/posts/5

app_name = "posts_app"

urlpatterns = [
    path("posts/", views.index, name="post-list"),
    path("posts/<int:post_id>", views.post_detail, name="post-detail"),
    path("posts/<int:post_id>/update", views.post_update, name="post-update"),
    path("posts/<int:post_id>/delete", views.post_delete, name="post-delete"),
    path("posts/new", views.post_create, name="post-create")
]

posts_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("posts_app.urls"))
]

postsncomments/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postsncomments_app', include("postsncomments_app.urls"))
]

post/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=1024)

    def __str__(self) -> str:
        return f"ID: {self.id} \nTitle: {self.title}"

class Comment(models.Model):
    body = models.CharField(max_length=1024)
    post = models.ForeignKey(Post,
    on_delete=models.CASCADE,
    related_name='comments')

    def __str__(self) -> str:
        return f"ID: {self.id} \nOn Post: {self.post}\nText: {self.body[:60]}..."

posts_and_comments/posts/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.CharField(max_length=600)


class Comment(models.Model):
    body = models.CharField(max_length=300)
    post = models.ForeignKey('Post',
                             on_delete=models.CASCADE,
                             related_name='comments')

post/posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Post, Comment

def get_post(post_id):
    return Post.objects.get(id=post_id)

def get_all_posts():
    return Post.objects.all()

def index(request):
    post_list = get_all_posts()
    post_data = {'posts':post_list}
    return render(request, 'posts/index.html', post_data)

def post_detail(request, post_id):
    post = get_post(post_id)
    try:
        post_comments = post.comments.all()
    except(KeyError, Comment.DoesNotExist):
        return render(request,
        'posts/detail.html',
        {
            'post':post,
            'error_message' : "This post has no comments."
        })
    else:
        
        post_comments_list = {'comments': post_comments, 'post' : post}
        return render(request,
        'posts/detail.html',
        post_comments_list)

posts_and_comments/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, Comment
from .util import get_post_by_id

# Create your views here.


def index(request):
    posts_list = Post.objects.all()
    context = {'posts_list': posts_list}
    return render(request, 'posts/index.html', context)


def post(request, id):
    current_post = get_post_by_id(id)
    context = {'current_post': current_post}
    return render(request, 'posts/post.html', context)

post/posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Post Details</title>
</head>
<body>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  {% csrf_token %}
  <h1> {{ post.title}} </h1>
  <hr>
  <h2>
    {{ post.body}}
  </h2>
  <ul>
    {% for comment in comments %}
      <li>
        <p>
        {{ comment.body }}
        </p>
      </li>
    {% endfor %}
</body>
</html>

post/posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Posts Mothership</title>
</head>
<body>
    <h1> All Posts </h1>
{% if posts %}
  <ul>
    {% for post in posts %}
      <li>
       <a href="{% url 'posts:post-detail' post.id %}">{{ post.title }}</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No posts are available.</p>
{% endif %}
</body>
</html>