post/post/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts_app/urls.py
from django.contrib import admin
from django.urls import path
from posts_app import views

# blog/posts/5

app_name = "posts_app"

urlpatterns = [
    path("posts/", views.index, name="post-list"),
    path("posts/<int:post_id>", views.post_detail, name="post-detail"),
    path("posts/<int:post_id>/update", views.post_update, name="post-update"),
    path("posts/<int:post_id>/delete", views.post_delete, name="post-delete"),
    path("posts/new", views.post_create, name="post-create")
]

posts_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("posts_app.urls"))
]

postsncomments/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postsncomments_app', include("postsncomments_app.urls"))
]

post/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=1024)

    def __str__(self) -> str:
        return f"ID: {self.id} \nTitle: {self.title}"

class Comment(models.Model):
    body = models.CharField(max_length=1024)
    post = models.ForeignKey(Post,
    on_delete=models.CASCADE,
    related_name='comments')

    def __str__(self) -> str:
        return f"ID: {self.id} \nOn Post: {self.post}\nText: {self.body[:60]}..."

posts_and_comments/posts/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.CharField(max_length=600)


class Comment(models.Model):
    body = models.CharField(max_length=300)
    post = models.ForeignKey('Post',
                             on_delete=models.CASCADE,
                             related_name='comments')

posts_app/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    body = models.CharField(max_length=128)
    name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.body}"

post/posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Post, Comment

def get_post(post_id):
    return Post.objects.get(id=post_id)

def get_all_posts():
    return Post.objects.all()

def index(request):
    post_list = get_all_posts()
    post_data = {'posts':post_list}
    return render(request, 'posts/index.html', post_data)

def post_detail(request, post_id):
    post = get_post(post_id)
    try:
        post_comments = post.comments.all()
    except(KeyError, Comment.DoesNotExist):
        return render(request,
        'posts/detail.html',
        {
            'post':post,
            'error_message' : "This post has no comments."
        })
    else:
        
        post_comments_list = {'comments': post_comments, 'post' : post}
        return render(request,
        'posts/detail.html',
        post_comments_list)

posts_and_comments/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, Comment
from .util import get_post_by_id

# Create your views here.


def index(request):
    posts_list = Post.objects.all()
    context = {'posts_list': posts_list}
    return render(request, 'posts/index.html', context)


def post(request, id):
    current_post = get_post_by_id(id)
    context = {'current_post': current_post}
    return render(request, 'posts/post.html', context)

posts_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from posts_app.models import Post

def index(request):
    stuff = {
        "posts": Post.objects.all()
    }
    return render(request, "posts/index.html", stuff)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    if post == None:
        HttpResponse("HEY, that post doesn't exist!")

    stuff = {
        "post": Post.objects.get(id=post_id)
    }
    return render(request, "posts/post_detail.html", stuff)

def post_create(request):
    print(request.method)

    # POST request
    if request.method == "POST":

        try: 
            new_post = Post()
            new_post.title = request.POST["title"]
            new_post.body = request.POST["body"]
            new_post.name = request.POST["name"]
            new_post.save()
        except:
            print("ERRRRORRRRR!!!")

        return HttpResponse("Hey, you created a post!")

    ## GET request
    return render(request, "posts/post_create.html")


def post_update(request, post_id):
    print(request.method)
    post = Post.objects.get(id=post_id)

    # POST request
    if request.method == "POST":
        try: 
            
            post.title = request.POST["title"]
            post.body = request.POST["body"]
            post.name = request.POST["name"]
            post.save()
        except:
            print("ERRRRORRRRR!!!")

        return HttpResponse("Hey, you created a post!")

    ## GET request
    data = {
        "post": post
    }
    return render(request, "posts/post_update.html", data)

def post_delete(request, post_id):
    post_to_delete = Post.objects.get(id=post_id)
    post_to_delete.delete()
    return HttpResponse("You successfully deleted this post.")

posts_app/templates/posts/index.html
<!DOCTYPE html>
<html>
<head>
  <title>My HTML Page</title>
</head>
<body>
  <nav id="body-nav">

  </nav>
  <main id="body-main">
    <ul>
    {% for post in posts %}
      <li><a href="{% url 'posts_app:post-detail' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
    </ul>
  </main>
  <footer id="body-footer">

  </footer>
</body>
</html>

posts_app/templates/posts/post_create.html
<!DOCTYPE html>
<html>
<head>
  <title>My HTML Page</title>
</head>
<body>
  <nav id="body-nav">

  </nav>
  <main id="body-main">
    <h1>Create a new post!</h1>
    <form action="{% url 'posts_app:post-create' %}" method="POST">
      {% csrf_token %}
      <label>Title: </label>
      <input id="title" name="title" placeholder="title"></input>
      <br/>
      <label>Body: </label>
      <input id="body" name="body" placeholder="enter text"></input>
      <br/>
      <label>Author: </label>
      <input id="name" name="name" placeholder="your name"></input>
      <br/>
      <button type="submit">Add</button>
    </form>
  </main>
  <footer id="body-footer">

  </footer>
</body>
</html>

posts_app/templates/posts/post_detail.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ post.title }}</title>
</head>
<body>
  <nav id="body-nav">

  </nav>
  <main id="body-main">
    <h1>{{ post.title }}</h1>
    <h2>{{ post.name }}</h2>
    <p>{{ post.body }}</p>
    {% for comment in post.comments.all %}
      <p><i>{{ comment.body }}</i> by {{ comment.name }}</p>
    {% endfor %}
  </main>
  <footer id="body-footer">

  </footer>
</body>
</html>

posts_app/templates/posts/post_update.html
<!DOCTYPE html>
<html>
<head>
  <title>My HTML Page</title>
</head>
<body>
  <nav id="body-nav">

  </nav>
  <main id="body-main">
    <h1>Create a new post!</h1>
    <form action="{% url 'posts_app:post-update' post.id %}" method="POST">
      {% csrf_token %}
      <label>Title: </label>
      <input id="title" name="title" placeholder="title" value="{{post.title}}"></input>
      <br/>
      <label>Body: </label>
      <input id="body" name="body" placeholder="enter text" value="{{post.body}}">></input>
      <br/>
      <label>Author: </label>
      <input id="name" name="name" placeholder="your name"></input>
      <br/>
      <button type="submit">Add</button>
    </form>
  </main>
  <footer id="body-footer">

  </footer>
</body>
</html>